# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True,
                                           serialize=False, unique=True)),
                ('order_id', models.CharField(max_length=255, unique=True)),
                ('marketplace', models.CharField(blank=True, max_length=255,
                                                 null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('items', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2,
                                               max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=4,
                                              null=True)),
                ('shipping', models.DecimalField(blank=True, decimal_places=2,
                                                 max_digits=10, null=True)),
            ],
        ),
    ]
